# Default values for flask-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
image:
  repository: rozdockerforever/simple_flask
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "flask_app_ubuntu"

service:
  type: NodePort
  port: 8080
