
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-pod
  template:
    metadata:
      labels:
        app: flask-pod
    spec:
      containers:
      - name: flask-pod
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3
