apiVersion: v1
kind: Service
metadata:
  name: flask-{{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - nodePort : {{ .Values.service.port }}
    port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: flask-pod
