#github ci action for flask app


name: Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check out on ubuntu machine
      uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file ./app/Dockerfile --tag rozdockerforever/simple_flask:flask_app_ubuntu

    - name: Run a flask conatiner
      run: docker run -d --name flask_app -p 3000:3000 rozdockerforever/simple_flask:flask_app_ubuntu
      
#     - name: Test Flask Container
#        run:|
#        curl_var=$(curl http://127.0.0.1:3000/?msg=test) 
#        if [ $(echo "${curl_var}") == "test" ]; then echo works; fi
       


#     - name: Push the image to the Docker Hub
#       uses: mr-smithers-excellent/docker-build-push@v5
#       with:
#         dockerfile: ./app/Dockerfile
#         registry: docker.io
#         tags: flask_app_ubuntu
#         image: rozdockerforever/simple_flask
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
