#github ci action for flask app


name: Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check out on ubuntu machine
      uses: actions/checkout@v2

    - name: Build and Push to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        dockerfile: ./app/Dockerfile
        registry: docker.io
        tags: flask_app_ubuntu
        image: rozdockerforever/simple_flask
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
